-- liquibase formatted sql
-- changeset tansen:1
-- preconditions onFail:CONTINUE onError:HALT
-- precondition-sql-check expectedResult:0 SELECT COUNT(*) from admin_roles
INSERT INTO admin_roles (description, icon, `name`, navigation, parent_name, permission, position, ui_group_name, version)
VALUES
    ('Root', '', 'Root', 'NONE', 'ROOT', 'NONE', 0, 'NONE', 0),

    ('Admins', 'UserCog ', 'Admin', '/admin', 'Root', 'ADMIN', 1, 'NONE', 0),
    ('Create Admin', '', 'Create Admin', '/create', 'Admin', 'CREATE_ADMIN', 1, 'Admin', 0),
    ('View Admin', '', 'View Admin', '/view', 'Admin', 'VIEW_ADMIN', 2, 'Admin', 0),
    ('Edit Admin', '', 'Edit Admin', '/edit', 'Admin', 'EDIT_ADMIN', 3, 'Admin', 0),
    ('Delete Admin', '', 'Delete Admin', '/delete', 'Admin', 'DELETE_ADMIN', 4, 'Admin', 0),
    ('Block Admin', '', 'Block Admin', '/block', 'Admin', 'BLOCK_ADMIN', 5, 'Admin', 0),
    ('Unblock Admin', '', 'Unblock Admin', '/unblock', 'Admin', 'UNBLOCK_ADMIN', 6, 'Admin', 0),
    ('Resend Admin Account Activation Link', '', 'Resend Admin Account Activation Link',
     '/resend-admin-account-activation-link', 'Admin', 'RESEND_ADMIN_ACCOUNT_ACTIVATION_LINK', 7, 'Admin', 0),
    ('Send Admin Password Reset Link', '', 'Send Admin Password Reset Link', '/send-admin-password-reset-link',
     'Admin', 'SEND_ADMIN_PASSWORD_RESET_LINK', 8, 'Admin', 0),
    ('Reset Admin Two Factor Authentication', '', 'Reset Admin Two Factor Authentication', '/reset-admin-2fa',
     'Admin', 'RESET_ADMIN_TWO_FACTOR_AUTHENTICATION', 9, 'Admin', 0),

    ('Authority', 'Building2', 'Authority', '/authority', 'Root', 'AUTHORITY', 2, 'NONE', 0),
    ('View All Authority', '', 'View All Authority', '/view', 'Authority', 'VIEW_ALL_AUTHORITY', 1, 'Authority', 0),
    ('Create Authority', '', 'Create Authority', '/create', 'Authority', 'CREATE_AUTHORITY', 2, 'Authority', 0),
    ('Edit Authority', '', 'Edit Authority', '/edit', 'Authority', 'EDIT_AUTHORITY', 3, 'Authority', 0),
    ('Block Authority', '', 'Block Authority', '/block', 'Authority', 'BLOCK_AUTHORITY', 4, 'Authority', 0),
    ('Unblock Authority', '', 'Unblock Authority', '/unblock-authority', 'Authority', 'UNBLOCK_AUTHORITY', 5, 'Authority', 0),
    ('Delete Authority', '', 'Delete Authority', '/delete-authority', 'Authority', 'DELETE_AUTHORITY', 6, 'Authority', 0),
    ('Send Authority Password Reset Link', '', 'Send Authority Password Reset Link', '/send-authority-password-reset-link', 'Authority',
     'SEND_AUTHORITY_PASSWORD_RESET_LINK', 7, 'Authority', 0),
    ('Reset Authority Two Factor Authentication', '', 'Reset Authority Two Factor Authentication', '/reset-authority-2fa', 'Authority',
     'RESET_AUTHORITY_TWO_FACTOR_AUTHENTICATION', 8, 'Authority', 0),
    ('Resend Authority Account Activation Link', '', 'Resend Authority Account Activation Link',
     '/resend-user-account-activation-link', 'Users', 'RESEND_USER_ACCOUNT_ACTIVATION_LINK', 9, 'Users', 0),

    ('Users', 'Users', 'Users', '/users', 'Root', 'USERS', 3, 'NONE', 0),
    ('View User', '', 'View User', '/view', 'Users', 'VIEW_USER', 1, 'Users', 0),
    ('Edit User', '', 'Edit User', '/edit', 'Users', 'EDIT_USER', 2, 'Users', 0),
    ('Block User', '', 'Block User', '/block', 'Users', 'BLOCK_USER', 3, 'Users', 0),
    ('Unblock User', '', 'Unblock User', '/unblock-user', 'Users', 'UNBLOCK_USER', 4, 'Users', 0),
    ('Delete User', '', 'Delete User', '/delete-user', 'Users', 'DELETE_USER', 5, 'Users', 0),
    ('Send User Password Reset Link', '', 'Send User Password Reset Link', '/send-user-password-reset-link', 'Users',
     'SEND_USER_PASSWORD_RESET_LINK', 5, 'Users', 0),
    ('Reset User Two Factor Authentication', '', 'Reset User Two Factor Authentication', '/reset-user-2fa', 'Users',
     'RESET_USER_TWO_FACTOR_AUTHENTICATION', 6, 'Users', 0),
    ('Resend User Account Activation Link', '', 'Resend User Account Activation Link',
     '/resend-user-account-activation-link', 'Users', 'RESEND_USER_ACCOUNT_ACTIVATION_LINK', 7, 'Users', 0),

    ('Settings', 'Settings', 'Settings', '/setting', 'Root', 'SETTING', 4, 'NONE', 0),
    ('Access Groups', 'Users', 'Access Groups', '/access-group', 'Settings',
     'ACCESS_GROUPS', 1, 'Settings', 0),
    ('Tax & Service Charges', 'TicketPercent', 'Tax & Service Charges', '/tax-and-service-charges', 'Settings',
     'TAX_&_SERVICE_CHARGES', 2, 'Settings', 0),
    ('System Configuration', 'MonitorCog', 'System Configuration', '/system-configuration', 'Settings',
     'SYSTEM_CONFIGURATION', 3, 'Settings', 0),
    ('Terms & Conditions', 'ReceiptText', 'Terms & Conditions', '/terms-and-conditions', 'Settings',
     'TERMS_&_CONDITIONS', 4, 'Settings', 0),
    ('Email Templates', 'Mails', 'Email Templates', '/email-templates', 'Settings',
     'EMAIL_TEMPLATE', 5, 'Settings', 0),
    ('View Email Template', '', 'View Email Template', '/view', 'Email Templates',
     'VIEW_EMAIL_TEMPLATE', 1, 'Email Templates', 0),
    ('Modify Email Template', '', 'Modify Email Template', '/edit', 'Email Templates',
     'MODIFY_EMAIL_TEMPLATE', 2, 'Email Templates', 0),
    ('SMS Templates', 'MessagesSquare', 'SMS Templates', '/sms-templates', 'Settings',
     'SMS_TEMPLATE', 6, 'Settings', 0),
    ('View SMS Template', '', 'View SMS Template', '/view', 'SMS Templates',
     'VIEW_SMS_TEMPLATE', 1, 'SMS Templates', 0),
    ('Modify SMS Template', '', 'Modify SMS Template', '/edit', 'SMS Templates',
     'MODIFY_SMS_TEMPLATE', 2, 'SMS Templates', 0),

    ('Logout', 'LogOut', 'Logout', '/logout', 'Root', 'LOGOUT', 999, 'COMMON', 0);
