spring:
  servlet:
    multipart:
      max-file-size: 55MB
      max-request-size: 55MB

  profiles:
    active: dev

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml
